//  top bar intial values
export const intialValueTop = [
  { id: "#ounce_top", name: "Gold", sub: "Ounce", unit: "$" },
  { id: "#gol18_top", name: "Gold", sub: "Gram", unit: "Toman" },
  { id: "#mithqal_top", name: "Gold", sub: "Mithqal", unit: "Toman" },
  { id: "#emami1_top", name: "Coin", sub: "Emami", unit: "Toman" },
  { id: "#eur1_top", name: "Euro", sub: "/IRR", unit: "Toman" },
  { id: "#usd1_top", name: "US Dollar", sub: "/IRR", unit: "Toman" },
];

// chart intial values
export const intialValueChart = [
  {
    code: "USD",
    name: "US Dollar",
    flagUrl: "usa.png",
    sellId: "usd1",
    buyId: "usd2",
    max: 30000,
  },
  {
    code: "EUR",
    name: "Euro",
    flagUrl: "euro.png",
    sellId: "eur1",
    buyId: "eur2",
    max: 32000,
  },
  {
    code: "GBP",
    name: "British Pound",
    flagUrl: "uk.png",
    sellId: "gbp1",
    buyId: "gbp2",
    max: 34900,
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    flagUrl: "russia.png",
    sellId: "rub1",
    buyId: "rub2",
    max: 500,
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    flagUrl: "turkey.png",
    sellId: "try1",
    buyId: "try2",
    max: 31000,
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    flagUrl: "china.png",
    sellId: "cny1",
    buyId: "cny2",
    max: 41000,
  },
  {
    code: "AED",
    name: "UAE Dirham",
    flagUrl: "uae.png",
    sellId: "aed1",
    buyId: "aed2",
    max: 7000,
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    flagUrl: "swiss.png",
    sellId: "chf1",
    buyId: "chf2",
    max: 30000,
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    flagUrl: "canada.png",
    sellId: "cad1",
    buyId: "cad2",
    max: 21000,
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    flagUrl: "australia.png",
    sellId: "aud1",
    buyId: "aud2",
    max: 19500,
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    flagUrl: "korona.png",
    sellId: "sek1",
    buyId: "sek2",
    max: 31000,
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    flagUrl: "norway.png",
    sellId: "nok2",
    buyId: "nok1",
    max: 3000,
  },

  {
    code: "THB",
    name: "Thai Baht",
    flagUrl: "thai.jpg",
    sellId: "thb1",
    buyId: "thb2",
    max: 1000,
  },
  {
    code: "SGD",
    name: "Singapor Dollar",
    flagUrl: "singapore.png",
    sellId: "sgd1",
    buyId: "sgd2",
    max: 19500,
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    flagUrl: "hong-kong.png",
    sellId: "hkd1",
    buyId: "hkd2",
    max: 3500,
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    flagUrl: "azerbaijan.png",
    sellId: "azn1",
    buyId: "azn2",
    max: 15500,
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    flagUrl: "armenia.png",
    sellId: "amd1",
    buyId: "amd2",
    max: 600,
  },
  {
    code: "AFG",
    name: "Afghanistan Afghani",
    flagUrl: "afghanistan.png",
    sellId: "afn1",
    buyId: "afn2",
    max: 400,
  },
  {
    code: "DKK",
    name: "Danish Krone",
    flagUrl: "denmark.png",
    sellId: "dkk1",
    buyId: "dkk2",
    max: 4500,
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    flagUrl: "japan.png",
    sellId: "jpy1",
    buyId: "jpy2",
    max: 3500,
  },
  {
    code: "SAR",
    name: "KSA Riyal",
    flagUrl: "saudi.png",
    sellId: "sar1",
    buyId: "sar2",
    max: 7500,
  },
  {
    code: "INR",
    name: "Indian Rupee",
    flagUrl: "india.png",
    sellId: "inr1",
    buyId: "inr2",
    max: 400,
  },
  {
    code: "MYR",
    name: "Ringgit",
    flagUrl: "malasya.png",
    sellId: "myr1",
    buyId: "myr2",
    max: 6500,
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    flagUrl: "kuwait.png",
    sellId: "kwd1",
    buyId: "kwd2",
    max: 84000,
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    flagUrl: "iraq.png",
    sellId: "iqd1",
    buyId: "iqd2",
    max: 2000,
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    flagUrl: "bahrain.png",
    sellId: "bhd1",
    buyId: "bhd2",
    max: 70000,
  },
  {
    code: "OMR",
    name: "Omani Rial",
    flagUrl: "oman.png",
    sellId: "omr1",
    buyId: "omr2",
    max: 70000,
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    flagUrl: "qatar.png",
    sellId: "qar1",
    buyId: "qar2",
    max: 7500,
  },
];
